version: "3.8"

services:

  postgres:
    # image: ivanlonel/postgis-with-extensions:14-3.1
    build:
      context: . # Use image from Dockerfile in current dir
      args:
        - BASE_IMAGE_TAG=14-3.1
        - LOCALE=pt_BR
        - ENCODING=UTF-8
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_filename=postgresql-%a.log
      - -c
      - log_rotation_age=1440
      - -c
      - log_truncate_on_rotation=on
      - -c
      - "datestyle=ISO, DMY"
      - -c
      - effective_cache_size=2048MB
      - -c
      - shared_buffers=256MB
      - -c
      - work_mem=8MB
      - -c
      - maintenance_work_mem=256MB
      - -c
      - track_counts=on
      - -c
      - autovacuum=on
    restart: always
    ports:
      - "5432:5432"
    shm_size: 2gb
    stop_grace_period: 2m30s
    environment:
      # LC_COLLATE=C makes strings comparison (and decurring operations like sorting) faster,
      #   because it's just byte-to-byte comparison (no complex locale rules)
      # LC_CTYPE=C would make Postgres features that use ctype.h
      #   (e.g. upper(), lower(), initcap(), ILIKE, citext) work as expected only for
      #   characters in the US-ASCII range (up to codepoint 0x7F in Unicode).
      - LANG=pt_BR.utf8
      - LC_COLLATE=C
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork
    secrets:
      - postgres-passwd

  powa-web:
    image: powateam/powa-web
    restart: always
    ports:
      - "8888:8888"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - powa-web.conf:/etc/powa-web.conf
    networks:
      - pgnetwork
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "80:80"
    entrypoint: /pgadmin_entrypoint.sh
    environment:
      - PGADMIN_DEFAULT_EMAIL_FILE=/run/secrets/pgadmin-email
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin-passwd
      - TZ=America/Sao_Paulo
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
      - ./pgadmin_entrypoint.sh:/pgadmin_entrypoint.sh
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork
    depends_on:
      - postgres
    secrets:
      - pgadmin-email
      - pgadmin-passwd

volumes:
  postgres_data:
  pgadmin4_data:

secrets:
  postgres-passwd:
    file: secrets/postgres-passwd.txt
  pgadmin-email:
    file: secrets/pgadmin-email.txt
  pgadmin-passwd:
    file: secrets/pgadmin-passwd.txt

networks:
  pgnetwork:
    driver: bridge
    ipam:
      # defining static IP range for network, so it can be referenced in pg_hba.conf
      driver: default
      config:
        - subnet: 172.24.240.0/24
